// <auto-generated />
using AutoMapper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapper.Migrations
{
    [DbContext(typeof(PersonalDetailsContext))]
    partial class PersonalDetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoMapper.model.PersonalDetail", b =>
                {
                    b.Property<int>("Adhaar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Adhaar"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Adhaar");

                    b.ToTable("PersonalDetalis");

                    b.HasData(
                        new
                        {
                            Adhaar = 12345,
                            Age = 12,
                            Name = "jb",
                            gender = "male"
                        },
                        new
                        {
                            Adhaar = 123456,
                            Age = 12,
                            Name = "jb",
                            gender = "male"
                        },
                        new
                        {
                            Adhaar = 123457,
                            Age = 12,
                            Name = "jb",
                            gender = "male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
